Update build-macos.yml
check directory

diff --git a/.github/workflows/build-macos.yml b/.github/workflows/build-macos.yml
--- a/.github/workflows/build-macos.yml
+++ b/.github/workflows/build-macos.yml
@@ -34,6 +34,12 @@ jobs:
       run: |
         conan remote add ultimaker-public https://ultimaker.jfrog.io/artifactory/api/conan/ultimaker-public-conan || true
 
+    - name: Debug working directory and list files
+      run: |
+        pwd
+        ls -lah
+        cat conanfile.py || echo "conanfile.py not found!"
+        
     - name: Build application with Conan
       run: |
         conan install . --build=missing \
